name: tree_state_machine
version: 0.5.0-beta
description: Hierachical state machine library. 
homepage: https://github.com/jlewicki/tree_state_machine

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  async: ^2.4.2
  meta: ^1.1.8
  rxdart: ^0.24.1

dev_dependencies:
  built_collection: ^4.3.0
  build_runner: ^1.10.2
  built_value: ^7.1.0
  built_value_generator: ^7.1.0
  json_annotation: ^3.0.0
  json_serializable: ^3.2.0
  path: ^1.6.4
  pedantic: ^1.9.2
  test: ^1.15.4
