name: tree_state_machine
description: Define and run hierarchical state machines in Dart and Flutter.
version: 3.0.0-dev.5
homepage: https://github.com/jlewicki/tree_state_machine

environment:
  sdk: ^3.2.1

dependencies:
  async: ^2.11.0
  collection: ^1.15.0 
  logging: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.7
  built_collection: ^5.0.0
  built_value: ^8.8.0
  built_value_generator: ^8.1.3
  json_annotation: ^4.3.0 
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.9
  