name: tree_state_machine
version: 0.1.0
description: Hierachical state machine library. 
authors:
  - John Lewicki <jlewicki@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  json_annotation: ^3.0.0

dev_dependencies:
  test: ^1.9.1
  async: ^2.4.0
  path: ^1.6.4
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
