name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: dart:stable-sdk

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: dart pub get
    - name: Run tests
      run: dart run test
    - name: Analyze
      run: dart analyze
